const approvedQuestions = [
  {
    id: 1,
    tags: ["Octobotics", "PierSight"],
    question: "What is the common investment thesis across both companies?",
    answer: "I am interested in both for the same reason: the hardware is not necessarily the end-product. Octobotics uses robots to repeatedly access industrial assets that are difficult or dangerous for humans to inspect. PierSight uses satellites to repeatedly observe maritime activity that is difficult to see reliably from the ground. If they execute, the valuable asset becomes the longitudinal data generated by those physical systems and the intelligence built on top of it. My broader thesis is that some of India's strongest deep-tech companies will use indigenous hardware to capture difficult physical-world data, then compound it into recurring intelligence."
  },
  {
    id: 2,
    tags: ["Octobotics", "PierSight"],
    question: "Why did you choose these two companies?",
    answer: "Both fit directly into the RDI Deep Technology theme, but they attack very different markets. Octobotics is a robotics and industrial-infrastructure bet; PierSight is a space and maritime-intelligence bet. What connects them is the path from difficult physical observation to recurring decision intelligence. I also like that both are early enough that major de-risking milestones still lie ahead, which is where venture investing can create outsized returns if the thesis is right."
  },
  {
    id: 3,
    tags: ["Octobotics", "PierSight"],
    question: "Which company has better non-linear economics?",
    answer: "PierSight has the larger theoretical non-linearity. One satellite observation can potentially be repackaged into security, sanctions, insurance and trading intelligence for several customers. Octobotics can also develop operating leverage, but physical inspections still require robots and field operations. For Octobotics, I want revenue and inspection capacity to grow faster than field headcount. For PierSight, I want recurring analytics revenue to grow faster than satellite count."
  },
  {
    id: 4,
    tags: ["Octobotics", "PierSight"],
    question: "Which company has the stronger moat today?",
    answer: "Neither has a fully formed moat yet. Octobotics has field experience, industrial know-how, reference customers and certification progress, but credible competitors exist. PierSight has scarce SAR capability, flight heritage and institutional access, but larger global SAR operators already exist. At this stage I would describe both as having a head start that needs to be converted into a moat, rather than claiming either already possesses an unassailable one."
  },
  {
    id: 5,
    tags: ["Octobotics", "PierSight"],
    question: "Which assumptions in the two theses are most fragile?",
    answer: "For Octobotics, the critical assumption is that enough of the robotics and software stack can be reused across asset classes so growth does not become custom engineering plus more field teams. For PierSight, the fragile assumption is that MATSYA can create enough value above raw imagery for customers to pay recurring intelligence subscriptions. If either company remains tied closely to the physical unit of delivery, inspections for Octobotics or satellite capacity for PierSight, the venture-scale case could weaken. The counterpoint I would keep open is whether India's cost advantage, export potential and increasing strategic importance of owning indigenous IP can themselves create enough upside even before software-like economics fully emerge. I would want to test that rather than assume software is the only path to a large outcome."
  },
  {
    id: 6,
    tags: ["Octobotics"],
    question: "Why do you believe it is an investable opportunity?",
    answer: "Critical infrastructure inspection is mandatory spend. Refineries, tanks, ships and rail assets already need inspection, so Octobotics does not have to create a new budget. Its opportunity is to replace a hazardous, labour-heavy workflow with robotic NDT. What makes the timing interesting is that it can potentially be backed before hazardous-area certification, wider deployment and international scale materially de-risk the company. The upside depends less on building a clever robot and more on creating operating leverage across a reusable inspection platform."
  },
  {
    id: 7,
    tags: ["Octobotics"],
    question: "How does it compare with its main competitors?",
    answer: "PetroBot is the closest Indian head-to-head competitor and appears further ahead on hazardous-area certification, with strategic backing from ONGC and HPCL. I view that as category validation rather than a reason to automatically reject Octobotics. Solinas is better funded but is more focused on internal pipe and utility inspection, while Gecko Robotics is the scaled global benchmark. The investment question is whether Octobotics can differentiate through platform reuse, customer execution, local economics, broader asset classes and international expansion. If primary customer diligence shows no meaningful differentiation against these competitors, I would reconsider the investment."
  },
  {
    id: 8,
    tags: ["Octobotics"],
    question: "Is it just a services business with robots?",
    answer: "It could be, and that could actually be part of its massive upside and differentiation. The services-led model is useful initially because industrial customers do not need to purchase an unfamiliar robot upfront. It lets Octobotics own the deployment experience, learn the customer's workflow and collect inspection data directly. But if doubling revenue eventually requires roughly doubling field engineers and robots, the company remains a technology-enabled inspection service. The venture case requires inspection output to rise materially faster than labour and, over time, for analytics and asset intelligence to add value above the physical inspection itself. It could be building a very unique model for this space, with the potential for a SaaS-like disruption on top of a services-led entry model."
  },
  {
    id: 9,
    tags: ["Octobotics"],
    question: "What could make the business non-linear?",
    answer: "The first source of leverage does not need to be SaaS. It can come from robotics itself. If one robot and field team can inspect six assets in the time they previously inspected three, revenue can grow faster than labour. The second layer is platform reuse across tanks, marine structures, rail or other assets. The third, longer-term layer is repeatedly collected condition data that could support predictive asset-health products."
  },
  {
    id: 10,
    tags: ["Octobotics"],
    question: "What is its real moat today?",
    answer: "I would not call any single technology component the moat. The current advantage is the combination of robotics, NDT domain knowledge, field deployment capability, certification work and trust with industrial customers. Hardware can be copied more easily than years of reliable operation inside hazardous industrial environments. The durable moat still has to be earned through certification, customer depth, platform reuse and potentially proprietary asset-condition history."
  },
  {
    id: 11,
    tags: ["Octobotics"],
    question: "What could become its moat over the next five years?",
    answer: "The strongest version is a combination of certification, workflow integration and longitudinal asset data. If Octobotics repeatedly inspects the same refinery, tank fleet or vessel, it can build a historical record of how those assets degrade. That could eventually improve defect detection and predictive maintenance. I treat this as upside rather than a current moat because data ownership, customer permissions and the actual predictive value still need to be proven."
  },
  {
    id: 12,
    tags: ["Octobotics"],
    question: "What would make you walk away from the investment?",
    answer: "My main kill criterion is linearity. If inspection capacity and revenue only grow by adding field engineers and robots in similar proportion, the company may be a good industrial business but not the venture-scale platform I am underwriting. I would also reconsider if certification does not materially expand the addressable pipeline, if each new vertical requires extensive custom engineering, or if customer calls show no meaningful competitive differentiation."
  },
  {
    id: 13,
    tags: ["Octobotics"],
    question: "What would you ask the founders in a 30-minute meeting?",
    answer: "I would start with unit economics and reuse. Walk me through the last ten inspection jobs, including price, fully loaded field cost and contribution margin. When you enter a new asset class, what percentage of the hardware, autonomy and software is reused? I would also ask for dated certification milestones, inspection throughput per robot, revenue per field engineer, customer repeat behaviour and exactly what rights the company retains over inspection data."
  },
  {
    id: 14,
    tags: ["Octobotics"],
    question: "What is the single most important metric you would track?",
    answer: "Revenue per field engineer is the simplest high-level test, supported by inspections per robot per month and contribution margin per inspection. If these improve with scale, robotics is creating operating leverage. If revenue growth remains closely correlated with hiring additional field teams, the company is scaling services rather than technology."
  },
  {
    id: 15,
    tags: ["Octobotics"],
    question: "What happens if larger competitors enter its markets aggressively?",
    answer: "That would weaken Octobotics' current market-access and local-service advantage. Gecko Robotics is the clearest global example because it already has greater scale, capital and technical maturity. PetroBot and Solinas are also credible domestic competitors. Octobotics therefore cannot depend permanently on being cheaper or locally available. Before competitors expand aggressively, it needs to establish customer trust, certifications, efficient field economics and data or workflow advantages that make replacement harder. If a larger competitor enters before those advantages develop, I would re-underwrite the thesis."
  },
  {
    id: 16,
    tags: ["Octobotics"],
    question: "What is the end-state you are underwriting?",
    answer: "I do not see the end-state primarily as a robot manufacturer. I see an asset-integrity platform for critical infrastructure. Robotic inspection is the collection layer. Repeated inspection creates condition history. The higher-value product can eventually become understanding how an asset is degrading, where intervention is needed and potentially what is likely to fail next. The important caveat is that I do not need that software layer to exist today for the investment to work, but I do need evidence that operational leverage is improving."
  },
  {
    id: 17,
    tags: ["PierSight"],
    question: "Why do you believe it is an investable opportunity?",
    answer: "Maritime surveillance is a proven global market, which lowers category risk. The opportunity is to build a lower-cost, maritime-focused observation system from India while the scaled constellation and intelligence layer are still early. SAR works through darkness and cloud, while AIS can be switched off or spoofed. If PierSight can combine persistent observation with an intelligence product that governments and commercial customers repeatedly pay for, the upside is much larger than selling satellite imagery alone."
  },
  {
    id: 18,
    tags: ["PierSight"],
    question: "How does it compare with its main competitors?",
    answer: "ICEYE and Capella Space are the strongest SAR incumbents, while Unseenlabs and HawkEye 360 address the maritime-surveillance problem through RF intelligence. ICEYE in particular already has substantial flight heritage, capital and maritime capability. PierSight should not try to win a general SAR technology race against them. Its case rests on a more focused maritime architecture, potentially lower economics for persistent monitoring, India and regional positioning, and eventually a proprietary history of vessel behaviour. If those advantages are not meaningful, PierSight risks becoming a smaller version of companies that are already further ahead."
  },
  {
    id: 19,
    tags: ["PierSight"],
    question: "Why should it own satellites if analytics is where much of the value may sit?",
    answer: "Ownership only makes sense if the satellites create inputs that materially improve the intelligence product, and PierSight can retain enough of the resulting data to train and improve its models. Owning the constellation can provide guaranteed capacity, control over collection frequency, same-pass sensor data, lower marginal input cost at scale and proprietary historical observations. Another scenario is that MATSYA does not need to work only on PierSight data. Accepting third-party data could actually make it a stronger platform. What matters is whether PierSight's own constellation measurably improves latency, accuracy, persistence or economics. It would be very interesting to understand how the founders see MATSYA evolving and how much of the company's eventual value they expect it to represent."
  },
  {
    id: 20,
    tags: ["PierSight"],
    question: "Why could MATSYA become more than a dashboard?",
    answer: "It becomes more than a dashboard when it produces information that is not visible directly in a SAR image. That could mean combining SAR, AIS, RF, vessel ownership, sanctions and behavioural history to identify anomalies, estimate risk or trigger an operational decision. The strongest proof would be customers acting on the intelligence without manually reinterpreting the raw image, integrating the output into their workflows and paying recurring subscriptions for those outputs."
  },
  {
    id: 21,
    tags: ["PierSight"],
    question: "What could make the business non-linear?",
    answer: "The same observation can have value to several customers. A Coast Guard may care that a vessel went dark, an insurer may care about its behavioural risk, a bank may care about sanctions exposure and a commodity trader may care about cargo flows. The observation is collected once but can generate several different intelligence products. The clearest test is whether recurring analytics revenue per satellite rises over time."
  },
  {
    id: 22,
    tags: ["PierSight"],
    question: "What would make you walk away from the investment?",
    answer: "I would walk if the company remains primarily a capacity business where additional revenue consistently requires excessively additional satellite capex after a certain point of time. I would also reconsider if MATSYA cannot create differentiated intelligence above commodity imagery, if customers are unwilling to pay for recurring analytics, or if the claimed maritime-specific architecture provides no meaningful cost, latency or persistence advantage. A delayed launch changes timing; failure of the intelligence economics changes the thesis."
  },
  {
    id: 23,
    tags: ["PierSight"],
    question: "Who are its best customers, and how does that support the 'Bloomberg Terminal for the ocean' vision?",
    answer: "I separate anchor customers from scalable customers. Navies, Coast Guards and national maritime agencies can provide the largest contracts, sovereign validation and potentially help support constellation economics. But they are slow and concentrated. Marine insurers, sanctions and compliance teams, trade-finance institutions and eventually commodity traders are more interesting for scalable recurring intelligence because the same underlying observations can be repackaged across many commercial workflows. That customer mix is what could eventually support the 'Bloomberg Terminal for the ocean' vision: one underlying maritime intelligence layer serving different decision-makers who ask different questions of the same data."
  },
  {
    id: 24,
    tags: ["PierSight"],
    question: "How can one satellite observation be monetised multiple times?",
    answer: "Consider a tanker observed in the Strait of Hormuz. A Coast Guard might buy a dark-vessel alert. An insurer might use its behavioural history when pricing risk. A bank financing cargo might use the same event as part of sanctions screening. A trader might use aggregate movements to understand physical supply. The underlying observation is non-rival. The economic opportunity comes from turning it into different answers for different customers, subject to sovereign or contractual restrictions on some datasets."
  },
  {
    id: 25,
    tags: ["PierSight"],
    question: "What does 'Bloomberg Terminal for the ocean' actually mean for PierSight?",
    answer: "It does not mean building another satellite-image marketplace. My end-state for PierSight is an intelligence layer through which important maritime decisions are made. Bloomberg became valuable by combining data, history and workflows rather than merely displaying market prices. PierSight could attempt something similar for vessel behaviour by combining persistent observation with AIS, external datasets, behavioural history, alerts and APIs. Coast Guards could use it for security, insurers for vessel risk, banks for sanctions and trade-finance decisions, and traders for physical-flow intelligence. The vision only becomes credible if customers increasingly pay PierSight for the intelligence layer rather than individual images."
  }
];
window.approvedQuestions = approvedQuestions;
